# Generated by Django 3.2.9 on 2021-11-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='static/img/cars')),
                ('extra_info', models.CharField(blank=True, max_length=35)),
                ('description', models.TextField()),
            ],
        ),
    ]
