# Generated by Django 3.2.9 on 2021-11-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(upload_to='static/img/cars/uploaded'),
        ),
    ]
