# Generated by Django 3.2.9 on 2021-11-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_car_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='extra_info',
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
