# Generated by Django 3.2.9 on 2021-12-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20211129_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
