# Generated by Django 3.2.9 on 2021-12-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(upload_to='static/img/uploaded/cars'),
        ),
    ]
