# Generated by Django 3.2.9 on 2021-11-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='color',
            field=models.CharField(default='black', max_length=25),
            preserve_default=False,
        ),
    ]
